openapi: 3.0.1
info:
  title: User-Service
  description: User Service API
  contact:
    name: Violet.io
    url: https://violet.io
  version: v1
servers:
- url: https://sandbox-api.violet.io/v1
tags:
- name: Access
  description: ""
- name: Orgs
  description: Org related entities
- name: Users
  description: User related entities
paths:
  /auth/token:
    get:
      tags:
      - Access
      summary: Refresh Token
      operationId: refreshToken
      parameters:
      - name: X-Violet-Token
        in: header
        schema:
          type: string
      - name: X-Violet-App-Secret
        in: header
        schema:
          type: string
      - name: X-Violet-App-Id
        in: header
        schema:
          type: integer
          format: int32
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RefreshTokenResponse'
  /login:
    post:
      tags:
      - Access
      summary: Login
      operationId: login
      parameters:
      - name: X-Violet-App-Secret
        in: header
        schema:
          type: string
      - name: X-Violet-App-Id
        in: header
        schema:
          type: integer
          format: int32
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
components:
  schemas:
    LoginResponse:
      required:
      - email
      - first_name
      - last_name
      - password
      - type
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        first_name:
          type: string
          description: The users first name
        last_name:
          type: string
          description: The users last name
        password:
          type: string
          description: The users raw desired password
        email:
          type: string
          description: The users unique email address
        type:
          type: string
          description: The allowed values for the user type
          enum:
          - ADMIN
          - MERCHANT
          - USER
          - DEVELOPER
          - INFLUENCER
        verified:
          type: boolean
          description: If a user has verified their emailed address
        status:
          type: string
          description: The status of the user
          enum:
          - INACTIVE
          - ACTIVE
          - DISABLED
        date_created:
          type: string
          description: Date of creation
          format: date-time
        date_last_modified:
          type: string
          description: Date of last update
          format: date-time
        roles:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/Role'
        tos_accepted:
          type: boolean
          description: Terms of Service Accepted
        payment_configured:
          type: boolean
          description: Is the Users Payment Settings Configured
        privacy_policy_accepted:
          type: boolean
          description: Privacy Policy Accepted
        country_code:
          type: string
          description: Country Code
          enum:
          - US
          - AU
          - AT
          - BE
          - CA
          - DK
          - FI
          - FR
          - DE
          - HK
          - IE
          - IT
          - JP
          - LU
          - MX
          - NL
          - NZ
          - NO
          - PT
          - SG
          - ES
          - SE
          - CH
          - GB
          - AF
          - AX
          - AL
          - DZ
          - AS
          - AD
          - AO
          - AI
          - AQ
          - AG
          - AR
          - AM
          - AW
          - AZ
          - BS
          - BH
          - BD
          - BB
          - BY
          - BZ
          - BJ
          - BM
          - BT
          - BO
          - BA
          - BW
          - BV
          - BR
          - IO
          - BN
          - BG
          - BF
          - BI
          - KH
          - CM
          - CV
          - KY
          - CF
          - TD
          - CL
          - CN
          - CX
          - CC
          - CO
          - KM
          - CG
          - CD
          - CK
          - CR
          - CI
          - HR
          - CU
          - CY
          - CZ
          - DJ
          - DM
          - DO
          - EC
          - EG
          - SV
          - GQ
          - ER
          - EE
          - ET
          - FK
          - FO
          - FJ
          - GF
          - PF
          - TF
          - GA
          - GM
          - GE
          - GH
          - GI
          - GR
          - GL
          - GD
          - GP
          - GU
          - GT
          - GG
          - GN
          - GW
          - GY
          - HT
          - HM
          - VA
          - HN
          - HU
          - IS
          - IN
          - ID
          - IR
          - IQ
          - IM
          - IL
          - JM
          - JE
          - JO
          - KZ
          - KE
          - KI
          - KP
          - KR
          - KW
          - KG
          - LA
          - LV
          - LB
          - LS
          - LR
          - LY
          - LI
          - LT
          - MO
          - MK
          - MG
          - MW
          - MY
          - MV
          - ML
          - MT
          - MH
          - MQ
          - MR
          - MU
          - YT
          - FM
          - MD
          - MC
          - MN
          - ME
          - MS
          - MA
          - MZ
          - MM
          - NA
          - NR
          - NP
          - AN
          - NC
          - NI
          - NE
          - NG
          - NU
          - NF
          - MP
          - OM
          - PK
          - PW
          - PS
          - PA
          - PG
          - PY
          - PE
          - PH
          - PN
          - PL
          - PR
          - QA
          - RE
          - RO
          - RU
          - RW
          - SH
          - KN
          - LC
          - PM
          - VC
          - WS
          - SM
          - ST
          - SA
          - SN
          - RS
          - SC
          - SL
          - SK
          - SI
          - SB
          - SO
          - ZA
          - GS
          - LK
          - SD
          - SR
          - SJ
          - SZ
          - SY
          - TW
          - TJ
          - TZ
          - TH
          - TL
          - TG
          - TK
          - TO
          - TT
          - TN
          - TR
          - TM
          - TC
          - TV
          - UG
          - UA
          - AE
          - UM
          - UY
          - UZ
          - VU
          - VE
          - VN
          - VG
          - VI
          - WF
          - EH
          - YE
          - ZM
          - ZW
        token:
          type: string
          description: Token
        refresh_token:
          type: string
          description: Refresh Token
        merchant_id:
          type: integer
          description: Merchant ID
          format: int32
        merchant_ids:
          type: array
          description: Merchant IDs
          items:
            type: integer
            format: int32
        store_url:
          type: string
          description: Store Url
      description: Login Response
    Permission:
      required:
      - name
      type: object
      properties:
        name:
          maxLength: 50
          minLength: 1
          type: string
          description: Name of the Permission
        description:
          maxLength: 255
          minLength: 0
          type: string
          description: Brief description of the Permission
    RefreshTokenResponse:
      required:
      - token
      type: object
      properties:
        token:
          type: string
          description: Token
      description: Refresh Token Response
    Role:
      required:
      - name
      type: object
      properties:
        name:
          maxLength: 50
          minLength: 1
          type: string
          description: Name of the Role
        permissions:
          uniqueItems: true
          type: array
          description: Permissions available to this Role
          items:
            $ref: '#/components/schemas/Permission'
    User:
      required:
      - email
      - first_name
      - last_name
      - password
      - type
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        first_name:
          type: string
          description: The users first name
        last_name:
          type: string
          description: The users last name
        password:
          type: string
          description: The users raw desired password
        email:
          type: string
          description: The users unique email address
        type:
          type: string
          description: The allowed values for the user type
          enum:
          - ADMIN
          - MERCHANT
          - USER
          - DEVELOPER
          - INFLUENCER
        verified:
          type: boolean
          description: If a user has verified their emailed address
        status:
          type: string
          description: The status of the user
          enum:
          - INACTIVE
          - ACTIVE
          - DISABLED
        date_created:
          type: string
          description: Date of creation
          format: date-time
        date_last_modified:
          type: string
          description: Date of last update
          format: date-time
        roles:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/Role'
        tos_accepted:
          type: boolean
          description: Terms of Service Accepted
        payment_configured:
          type: boolean
          description: Is the Users Payment Settings Configured
        privacy_policy_accepted:
          type: boolean
          description: Privacy Policy Accepted
        country_code:
          type: string
          description: Country Code
          enum:
          - US
          - AU
          - AT
          - BE
          - CA
          - DK
          - FI
          - FR
          - DE
          - HK
          - IE
          - IT
          - JP
          - LU
          - MX
          - NL
          - NZ
          - NO
          - PT
          - SG
          - ES
          - SE
          - CH
          - GB
          - AF
          - AX
          - AL
          - DZ
          - AS
          - AD
          - AO
          - AI
          - AQ
          - AG
          - AR
          - AM
          - AW
          - AZ
          - BS
          - BH
          - BD
          - BB
          - BY
          - BZ
          - BJ
          - BM
          - BT
          - BO
          - BA
          - BW
          - BV
          - BR
          - IO
          - BN
          - BG
          - BF
          - BI
          - KH
          - CM
          - CV
          - KY
          - CF
          - TD
          - CL
          - CN
          - CX
          - CC
          - CO
          - KM
          - CG
          - CD
          - CK
          - CR
          - CI
          - HR
          - CU
          - CY
          - CZ
          - DJ
          - DM
          - DO
          - EC
          - EG
          - SV
          - GQ
          - ER
          - EE
          - ET
          - FK
          - FO
          - FJ
          - GF
          - PF
          - TF
          - GA
          - GM
          - GE
          - GH
          - GI
          - GR
          - GL
          - GD
          - GP
          - GU
          - GT
          - GG
          - GN
          - GW
          - GY
          - HT
          - HM
          - VA
          - HN
          - HU
          - IS
          - IN
          - ID
          - IR
          - IQ
          - IM
          - IL
          - JM
          - JE
          - JO
          - KZ
          - KE
          - KI
          - KP
          - KR
          - KW
          - KG
          - LA
          - LV
          - LB
          - LS
          - LR
          - LY
          - LI
          - LT
          - MO
          - MK
          - MG
          - MW
          - MY
          - MV
          - ML
          - MT
          - MH
          - MQ
          - MR
          - MU
          - YT
          - FM
          - MD
          - MC
          - MN
          - ME
          - MS
          - MA
          - MZ
          - MM
          - NA
          - NR
          - NP
          - AN
          - NC
          - NI
          - NE
          - NG
          - NU
          - NF
          - MP
          - OM
          - PK
          - PW
          - PS
          - PA
          - PG
          - PY
          - PE
          - PH
          - PN
          - PL
          - PR
          - QA
          - RE
          - RO
          - RU
          - RW
          - SH
          - KN
          - LC
          - PM
          - VC
          - WS
          - SM
          - ST
          - SA
          - SN
          - RS
          - SC
          - SL
          - SK
          - SI
          - SB
          - SO
          - ZA
          - GS
          - LK
          - SD
          - SR
          - SJ
          - SZ
          - SY
          - TW
          - TJ
          - TZ
          - TH
          - TL
          - TG
          - TK
          - TO
          - TT
          - TN
          - TR
          - TM
          - TC
          - TV
          - UG
          - UA
          - AE
          - UM
          - UY
          - UZ
          - VU
          - VE
          - VN
          - VG
          - VI
          - WF
          - EH
          - YE
          - ZM
          - ZW
      description: User account associated with store.
